services:
  postgres:
    image: postgres:17
    container_name: service-person
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: service-person
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

