version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: service-person
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: