server:
  port: 8081

spring:
  application:
    name: individuals-api

  datasource:
    url: jdbc:postgresql://keycloak-postgres:5432/keycloak
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true