server:
  port: 8098

spring:
  application:
    name: service-person

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres-person
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: public
    database: postgresql

  envers:
    enabled: true
    store_data_at_delete: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: false # пока временно отключил метрику после отладки поставить true
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.flywaydb: DEBUG

  # Url на который будет уходить запрос в person-service сервис
feignClientUrl: http://inventory:8080/api